In [50]:
import numpy as np
import pandas as pd

df = pd.read_csv("C:/Users/adjel/OneDrive/Desktop/Strava analysis/data/raw/activities.csv")

In [51]:
df.columns

Index(['resource_state', 'name', 'distance', 'moving_time', 'elapsed_time',
       'total_elevation_gain', 'type', 'sport_type', 'workout_type',
       'device_name', 'id', 'id_str', 'start_date', 'start_date_local',
       'timezone', 'utc_offset', 'location_city', 'location_state',
       'location_country', 'achievement_count', 'kudos_count', 'comment_count',
       'athlete_count', 'photo_count', 'trainer', 'commute', 'manual',
       'private', 'visibility', 'flagged', 'gear_id', 'start_latlng',
       'end_latlng', 'average_speed', 'max_speed', 'average_cadence',
       'average_watts', 'max_watts', 'weighted_average_watts', 'device_watts',
       'kilojoules', 'has_heartrate', 'average_heartrate', 'max_heartrate',
       'heartrate_opt_out', 'display_hide_heartrate_option', 'elev_high',
       'elev_low', 'upload_id', 'upload_id_str', 'external_id',
       'from_accepted_tag', 'pr_count', 'total_photo_count', 'has_kudoed',
       'suffer_score', 'athlete.id', 'athlete.id_str',
       'athlete.resource_state', 'map.id', 'map.summary_polyline',
       'map.resource_state'],
      dtype='object')

In [55]:
df.head()

,resource_state,name,distance,moving_time,elapsed_time,total_elevation_gain,type,sport_type,workout_type,device_name,...,pr_count,total_photo_count,has_kudoed,suffer_score,athlete.id,athlete.id_str,athlete.resource_state,map.id,map.summary_polyline,map.resource_state
0,2,Evening Run,5008.0,2011,2085,40.0,Run,Run,3.0,Garmin Forerunner 255,...,0,0,False,8.0,90405244,90405244,1,a19217754830,ykp}HtdkI]^cBdA_@^k@ZoA`Ai@Jk@BQ?IBKROd@?LOCKo...,2
1,2,Evening Ride,38025.2,5352,5429,373.0,Ride,Ride,NaN,Garmin Forerunner 255,...,6,0,False,23.0,90405244,90405244,1,a19181098123,oyc}Hp~vI~AyDn@g@`Bm@p@_GPOfQrG~G?PgOd@aBjAgBJ...,2
2,2,Evening Run,6015.4,2148,2148,64.0,Run,Run,3.0,Garmin Forerunner 255,...,0,0,False,11.0,90405244,90405244,1,a19155240969,ijc}HzowIVAFEf@}@FGnCsA|@s@bAg@v@cArC{DtAk@h@Y...,2
3,2,Lunch Run,5013.7,1649,1649,47.0,Run,Run,3.0,Garmin Forerunner 255,...,0,0,False,20.0,90405244,90405244,1,a19097377224,}jc}H~owIp@OPQVg@TSbCgAXS^]z@e@TUt@kAl@q@v@gAL...,2
4,2,Last evening in DD,6475.9,4440,4455,153.0,Walk,Walk,NaN,Garmin Forerunner 255,...,0,2,False,8.0,90405244,90405244,1,a19002170755,ib~eI`dcIJXLLVFX\LB\IhAHV?VORa@BAJ|@GfA@LBDl@g...,2

Units need to be converted to more usable ones, currently they look to be: distance:metres, time:seconds
workout_type looks to be a numerical version of the option on strava for workout, race, commute etc.
There are codes to get location data
heart rate data, lat and long

In [56]:
df.shape

(369, 62)

369 activities to analyse, 62 columns

In [54]:
df.tail()

,resource_state,name,distance,moving_time,elapsed_time,total_elevation_gain,type,sport_type,workout_type,device_name,...,pr_count,total_photo_count,has_kudoed,suffer_score,athlete.id,athlete.id_str,athlete.resource_state,map.id,map.summary_polyline,map.resource_state
364,2,Lunch Ride,124937.0,22007,441872,361.9,Ride,Ride,10.0,Strava App,...,0,0,False,NaN,90405244,90405244,1,a5856495212,}c~dIhzdQvETtCmDdA^fBrMfMl^lCLiAfF~AhJtFaCFlBw...,2
365,2,Evening Run,4359.2,1832,1846,75.3,Run,Run,0.0,Strava App,...,2,0,False,NaN,90405244,90405244,1,a5809128074,g}}eIznbI?QNl@CLSHm@`@[j@G?YPI@OAUKOA[HEDEJ?PS...,2
366,2,Evening Run,4896.2,2010,2019,90.3,Run,Run,0.0,Strava App,...,5,0,False,64.0,90405244,90405244,1,a5798445157,m}}eIbnbIJfAAh@ELMHa@l@WXOTWKQAQ@KCQQG[GICA]CI...,2
367,2,Evening Run,4984.4,2032,2036,95.4,Run,Run,0.0,Strava App,...,7,0,False,53.0,90405244,90405244,1,a5792611451,i}}eIhnbI@BF@ARDl@?`@GRgA~@QXEBYIQBMEa@]OUGEQE...,2
368,2,Afternoon Run,4621.1,2102,2171,84.1,Run,Run,3.0,Strava App,...,0,0,False,67.0,90405244,90405244,1,a5775923230,q}}eI|nbIJ@AALbACN]b@i@h@SH_@HSCUUICYCEBOLIb@U...,2